### ISSUE TITLE
[proposal] Additional information for file name normalization

### ISSUE THREAD

**Issue by llange** [konnectors/impots#168]
As some of the files I synchronized were not fully named (some ids were showing instead), I checked the document naming on the impots website. Here is a proposal for additional (or modified) values.

For typeImpot parameter, I propose a new value for categoryMap:
`'4': 'PrélèvementsSociaux',`

For typeDoc parameter, it may be possible to update values for documentTypeMap:
```
'1': 'DéclarationEnLigne',
...
'5': 'Déclaration',
```
(May be it's a deliberate choice not to show this as more and more declarations will be "Déclaration en ligne". Also having "Formulaire" instead of "Déclaration" seems delibarate, but this was not visible in comments. I personally prefer "Déclaration" as it is the same vocabulary as on the impots website.)

For typeForm parameter, I propose the following new or updated values for formTypeMap:
```
'1': 'Primitif',
'1TIP': 'PrimitifPrélevé'
'3': 'Dégrèvement',
'811': 'PremierAcompte',
'812': 'SecondAcompte',
```
I don't have one, but I imagine that '1MEN' stand for "mensualisé / mensualisation".
Would it be useful to add this info ? (Like : 'PrimitifMensualisé')

If there is interest in (all or part of) these updates, please tell : I will be happy to submit a Pull Request.

**Comment by LucsT** [comment]
Hi. 
Sure there is interest. I prepared some tools in cozy-konnector-libs for quick and auto renaming. We need them for a long time, and impots is a perfect example.
If you are confortable with doing a PR, let's do it. I'm not sure about the change of wording about 'Déclaration', let me check internally.
I will post a message again when auto-renaming will be ready.

On peut aussi s'exprimer en francais sans problème.

**Comment by llange** [comment]
Perfect, let me do that ! / Parfait, je me lance !

**Comment by llange** [comment]
PR prête pour relecture et discussion : #174

**Comment by llange** [comment]
Hi @LucsT , any chance some can do a review of #174 ?
By the way, did you have any internal feedback on the wording change ?
Merci !

**Comment by llange** [comment]
Closing this issue because the new website does not give us this kind of info anymore
